const slides=[
    {
        id:1,
        image:'./images/11.jpg',
    },
    {
        id:2,
        image:'./images/m22.jpeg',
    },
    {
        id:3,
        image:'./images/m33.jpeg',
    },
    {
        id:4,
        image:'./images/m44.jpeg',
    },
    {
        id:5,
        image:'./images/m55.jpeg',
    },
    {
        id:6,
        image:'./images/m66.jpeg',
    },
    {
        id:7,
        image:'./images/m77.jpeg',
    },
    {
        id:8,
        image:'./images/m88.jpeg',
    },
    {
        id:9,
        image:'./images/m99.jpeg',
    },
    
];
export default slides;